# Copyright (C) 2020-2021 Robin Krahl <robin.krahl@ireas.org>
# SPDX-License-Identifier: CC0-1.0
image: archlinux
packages:
  - gnupg
  - reuse
  - rustup
  - ttf-liberation
sources:
  - https://git.sr.ht/~ireas/genpdf-rs
tasks:
  - setup: |
      rustup set profile minimal
      rustup default stable
      rustup component add rustfmt
      rustup component add clippy
  - version: |
      rustc -V
  - verify: |
      cd genpdf-rs
      curl -s "https://pgp.ireas.org/0x6D533958F070C57C.txt" | gpg --import
      git verify-commit HEAD || [ `git config user.email` == "builds@sr.ht" ]
  - reuse: |
      cd genpdf-rs
      reuse lint
  - build: |
      cd genpdf-rs
      cargo build --release --all-targets
      cargo build --release --all-targets --all-features
  - test: |
      cd genpdf-rs
      cargo test --all-features
  - clippy: |
      cd genpdf-rs
      cargo clippy --all-features -- -D warnings
  - format: |
      cd genpdf-rs
      cargo fmt -- --check
triggers:
  - action: email
    condition: failure
    to: robin.krahl@ireas.org
